### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by fgvbrt** [openai/retro-baselines#2]
Hi, I created container and tried to run it, but get error. Below are docker logs:
Do I need to add something to container?

Thanks in advance

Traceback (most recent call last):
  File "/root/compo/agent.py", line 38, in <module>
    main()
  File "/root/compo/agent.py", line 24, in main
    env=DummyVecEnv([make_env]),
  File "/root/venv/lib/python3.5/site-packages/baselines/common/vec_env/dummy_vec_env.py", line 7, in __init__
    self.envs = [fn() for fn in env_fns]
  File "/root/venv/lib/python3.5/site-packages/baselines/common/vec_env/dummy_vec_env.py", line 7, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "/root/compo/sonic_util.py", line 15, in make_env
    env = grc.RemoteEnv('tmp/sock')
  File "/root/venv/lib/python3.5/site-packages/gym_remote/client.py", line 9, in __init__
    self.bridge.connect()
  File "/root/venv/lib/python3.5/site-packages/gym_remote/bridge.py", line 251, in connect
    self.sock.connect(sock_path)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by praveen-palanisamy** [comment]
Looks like you are trying to run the agent in a docker container locally. The agents in this repository expect a gym remote environment to exist. 

You have two options:
1. Run the remote env that the `retro-baseline/agents` expect by default.
2. Modify the agent code (mainly the `sonic_util.py`) to use a local gym environment.

For the first option, you can use `retro-contest run --agent <DOCKER-IMG-TAG> --results-dir <RESULTS-DIR> <GAME-NAME>  <LEVEL-NAME>`. 
`retro-contest` runs the necessary remote environment as well as launches the agent container.

For the second option, you can use the gym environment from [https://github.com/openai/retro](https://github.com/openai/retro) or install [`retro-contest`](https://github.com/openai/retro-contest) and use `retro_contest.local.make(...)` to create a local gym environment. 

Refer to the contest details page for more information: [https://contest.openai.com/details](https://contest.openai.com/details)

**Comment by fgvbrt** [comment]
Hi, thanks. 
Am i right that for the first option I will be able to train agent only on one environment?

**Comment by praveen-palanisamy** [comment]
Yes. You are right about the first option.
